// Destructing

// let names=['Manish','Anish','Danish','Nish'];
// let[first,second,third]=names;
// let[last,...others]=names;

// console.log(first,second,third);
// console.log(last,...others);


// destrution in objects

// const student_data={
// name:'Manish',
// Address:'Bharatpur',
// subject:['Math','Science','CS'],
// contact:9845452525,

// };
// // let {name,Address}=student_data
// let{name:firstname,place="trichowk",contact:phone=9844210321}=student_data;
// console.log(firstname,place,phone);